# Đây là nền tảng nền tảng hỗ trợ tài nguyên

github: # Replace with up to 4 GitHub Sponsors-enabled usernames e.g., [user1, user2]
open_collective      : # Thay thế bằng một người dùng duy nhất Mở Tên tập thể: Ngô Quang Thông
ko_fi          : # Thay thế bằng Ko-fi duy nhất tên người dùng: Ngô Quang Thông
tidelift        : # Thay thế bằng nền tảng tên-nền / gói-tên-gói duy nhất Tidelift, ví dụ: npm / babe
Community_bridge  : # Thay thế bằng một dự án tên duy nhất Community Bridge, ví dụ: cloud-Foundry
liberapay: # Replace with a single Liberapay username
issuehunt: # Replace with a single IssueHunt username
otechie: # Replace with a single Otechie username
chỉnh sửa                        : # Thay thế bằng URL ngoquangthong
Trong khi đó, bạn sẽ không gặp khó khăn gì.  
